### ISSUE TITLE
Revisiting Debye-Waller/B factors

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#105]
Just passed through my mind that we should check this is implemented correctly....

**Comment by hakonanes** [comment]
You might be aware of this, but this can be set upon initializing a structure library with `diffpy.structure.Atom.Bisoequiv` per atom (https://www.diffpy.org/diffpy.structure/mod_atom.html?highlight=bisoequiv#diffpy.structure.atom.Atom.Bisoequiv).

**Comment by dnjohnstone** [comment]
Thanks for that, I hadn't thought of that but you're absolutely correct we should definitely be defining that in the `diffpy.structure` and then getting it from there - I think you're about to resolve this with your `ReciprocalLatticePoint` class, so that should be really good too.

**Comment by hakonanes** [comment]
Yes, I think this is cleanest.

As a bonus, when a phase is saved in the orix HDF5 file, what you put into this Bisoequiv property gets written to the U 3x3 matrix, and subsequently read again when read.

**Comment by dnjohnstone** [comment]
Is this going to be considered resolved by #111 ?

**Comment by hakonanes** [comment]
> Is this going to be considered resolved by #111 ?

I don't know, unfortunately I don't have the time to make use of the ReciprocalLatticePoint (rlp) class in other parts of diffsims in that PR, only to implement it and for it to be part of the code. I want it in now because I use it for kikuchipy (https://github.com/pyxem/kikuchipy/pull/204). (Parts of that should go into diffsims as well, in future.)

The factors can easily be set by the user via `ReciprocalLatticePoint.phase.structure.Bisoequiv` (a list of Debye Waller factors the length of number of atoms), and of course easily used from there.

**Comment by dnjohnstone** [comment]
Great, thanks!
