### ISSUE TITLE
Why are the template libraries so huge? Best way to sample orientations?

### ISSUE THREAD

**Issue by din14970** [pyxem/diffsims#124]
More of a discussion question.

I'm trying to use pyxem/diffsims/orix for orientation mapping with template matching mainly as an alternative to Astar. However, I've found that the indexing of the same dataset is one to three orders of magnitude slower. This got me digging a bit into the generation of the template libraries.

If I generate a library from a rotation list `rotation_list_generators.get_fundamental_zone_grid(225, 2)`, I need to simulate about 350k templates  and when I index a map of 200x200 with this library this takes many many hours - I suppose because at each pixel it is comparing the DP to each template? So I've resorted to decreasing the sampling substantially in generating the template library. But if I choose something like `rotation_list_generators.get_fundamental_zone_grid(225, 10)`, the IPF-Z plot of the rotations looks really sparse, and I still have more than 2000 templates.

What I wonder is how is Astar able to do this so much faster and still with decent results. Maybe part of the answer is the slowness of python, but I think there's more to it. When I make a library in Astar using the default settings, I get a library of about 1300 templates. Yet they still claim an angular resolution of 1 degree. Indexation of a single pixel is nearly instantaneous and I get an IPF view of the match index with all the other templates. 

Is diffsims sampling orientation space in a really inefficient way? Or is Astar doing things completely differently? 1300 seems like just points to make a fine grid on the 001 - 101 - 111 triangle, but not enough to cover all possible rotations around these zones. My (very non-scientific) feeling is that Astar is just creating a grid of orientations inside the triangle, simulating the DP's on this grid, and rotating the templates to match the experimental DP's during the indexation process. The additional rotation of the template can then be taken into consideration into the indexation. If there is a fast way to rotate the template into agreement with the DP, maybe with some kind of transform similar to a Hough transform, then I guess the library can be generated much more quickly and indexation could be faster too?

**Comment by pc494** [comment]
Good question, I'll try and keep my answer to a sensible length. Before then, for the avoidance of doubt, I must state that Index (from Nanomegas) is propriety closed source code, and the discussions that follow about "what it does" are merely speculation. 

The gridding that we use from orix is consistent with those used in EMSOFT and MTEX (primarily EBSD software) [1], with timings and sizes (for dictionary based indexing) reflective of those seen in the open literature [2].

For spot patterns, a time saving option is to exploit the intensity similarity when a sample is radially integrated, as discussed in [3]. This method is also used by Morawiec [4] and gives "grid sizes" broadly consistent with those reported by Index. This is the idea @din14970 alludes to in his final paragraph. This could be implemented within diffsims/pyxem, but the people working on that side of the code have never seemed that enthusiastic about it.

My personal lack of enthusiasm has been due to a range of fairly nice work arounds that exist, using local grids (for small rotations) or virtual imaging [5] for grain mapping.

[1] - https://github.com/pyxem/orix/pull/90#issuecomment-671057190
[2] - Chen et al. https://arxiv.org/abs/1502.07436
[3] - Wu et al. 10.1016/j.ultramic.2009.06.002
[4] - 10.1016/j.ultramic.2013.08.008
[5] - Bergh et al. DOI:10.1111/jmi.12850

**Comment by din14970** [comment]
Thanks for the references; things I need to look into!

> Index (from Nanomegas) is propriety closed source code, and the discussions that follow about "what it does" are merely speculation.

Precisely why I want to move away from it and find an open source alternative - just out of principle I think we as scientists should know exactly what happens when we analyze our data. I thought that maybe people who've spent time making these types of applications could make a sensible guess about how the Nanomegas software is working under the hood.

> My personal lack of enthusiasm has been due to a range of fairly nice work arounds that exist, using local grids (for small rotations) or virtual imaging [5] for grain mapping.

I found this paper before; very cool work! I'm actually dealing with a related scientific issue which I would have liked to resolve entirely with pyxem: orientations of small precipitates embedded in a crystalline matrix. While the segmentation part is cool, actually doing the template matching to find the orientations is too slow which is a pitty. This is mainly because the precipitate phase has quite a complex crystal structure, so it takes forever to calculate the library and even longer to do the indexing.

While it may be less cool, I think that many more users might be attracted to these tools if Astar-like functionality and performance were available. But I understand that you guys are pretty busy and working on things relevant to your research. Maybe I will look into it myself; if I manage to figure it out and if you are interested I'll make a PR. Might take a while though, I'm more of an amateur.

**Comment by pc494** [comment]
To your first point, I would agree, although people have made efforts to investigate what ASTAR does it's always caveated with "we think", at least with diffsims/orix/pyxem we do know. My "thought" on how ASTAR keep their templates libraries so small is the method of Wu, but (unsurprisingly) we've never confirmed that.

That sounds like exciting work! Feel free to reach out to me if you want to discuss specifics (the pyxem email is probably best just to keep the team in the loop). I agree that our code speed at present isn't competitive with the commercial software, and I think making a user friendly experience will be essential for the long term health of the package. If you do decide to work on extending it, please reach out early and often, it's much easier (and part of the purpose of doing OSS) if everyone pulls in the same direction.

**Comment by pc494** [comment]
Closing this as an issue, but if anyone subsequently stumbles upon this, the conversation started here became a project that eventually became a manuscript (under review at time of writing)!
