### ISSUE TITLE
Select more natural corners for the streographic triangle (hexagonal system)

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#168]
From #167:

"I would also suggest a small edit to the crystal_system_dictionary for the hexagonal system which I've been dealing with recently. In my view, the coordinates for the coordinates of the fundamental zone should be [(0, 0, 0, 1), (1, 0, -1, 0), (2, -1, -1, 0)], at least when making a templates grid."

> The plane normals suggested by @din14970 seem reasonable:
> ![m1](https://user-images.githubusercontent.com/12139781/119660539-aa9ba700-be2f-11eb-95d2-c185da4fe58e.png)
> ![m2](https://user-images.githubusercontent.com/12139781/119660541-ab343d80-be2f-11eb-82a6-61ffa46fb77c.png)

**Comment by hakonanes** [comment]
Good. I ment crystal directions in that comment...

I assume that dictionary can be replaced by `SphericalRegion.vertices` which I hope to implement in orix soon, https://github.com/pyxem/orix/issues/169? If there is any interest in that, I can try to get the code I have locally finished and make a PR to orix soon.

**Comment by din14970** [comment]
@hakonanes I think if we can get rid of the sketchy dictionary in diffsims and replace it with something a bit more robust it's probably good. However, something that must be kept clear is what the zone really represents. If it is the "set of unique beam directions" as used in an IPF color key, this is still something else than the set of unique orientations with the constraint `phi_1 = 0`, because if the crystal has inversion symmetry some identical beam directions can still produce orientations that are not related to each other by a `phi_1` rotation but a rotation and an inversion. In the example of template matching, this manifests as mirrored templates. For generating the template library, I still only use the "fundamental" beam-directions orientations to conserve memory and time calculating the templates, but during the indexation step I also mirror the templates and match those as well. While the difference is very slight, there is always a clear preference:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/25320842/119959617-73023b80-bfa4-11eb-8b20-1b52fdb94dd7.png">
What is therefore very important is that the Euler angles corresponding to the templates  in the mirrored sector are correct: they should match the templates mirrored across the x axis (to calculate them I basically reverse theta). For this to be the case, in the current implementation my fundamental zone should always have the corners `[001]`, a vector `[x01]` with x>0 and `[yz1]` with z>0 and no constraint on y.

**Comment by pc494** [comment]
This code is now orix's problem
