### ISSUE TITLE
Weird behavior DiffractionSimulation.intensities

### ISSUE THREAD

**Issue by din14970** [pyxem/diffsims#174]
**Describe the bug**
Due to the way `intensities` is implemented as a property with a setter, some weird behavior can occur due to the direct beam mask.

Similar issues can be created with the `coordinates` attribute.

**To Reproduce**
```python
from diffsims.sims.diffraction_simulation import DiffractionSimulation

coords = np.array([[0, 0], [1, 1], [2, 3]])
intensities = np.array([1, 1, 3])
sim = DiffractionSimulation(coordinates = coords, intensities = intensities, with_direct_beam=False)
sim.intensities = sim.intensities

# now throws an error because intensities is of the wrong shape
sim.intensities
```

**Expected behavior**
The setter needs to be more restrictive so that not just any array can be used, which creates inconsistencies.
I propose to check the size of the passed arrays and modify behavior depending on whether `with_direct_beam` is on or not.

**Comment by hakonanes** [comment]
Sounds good to me. What is the "ground truth" when it comes to shape here, the coordinates? Would be good to check the intensities array shape against the coordinates array shape upon setting these.

Looks like there are some other things in `DiffractionSimulation` which can be cleaned up, like unnecessary setting of private attributes in `__init__` (since they are set upon the call to `self.coordinates`):

https://github.com/pyxem/diffsims/blob/3c2540e520f7c8a6a60d24ec9b88844c4d2c8f83/diffsims/sims/diffraction_simulation.py#L57-L65

**Comment by hakonanes** [comment]
I've marked this as a bug, because `sim.intensities = sim.intensities` shouldn't result in an error. Thus, this could go in a v0.4.3 patch release, if there is interest. Or, we could wait for a v0.5 release which could be released soon (a week or two?) because there are a few unreleased features in (see changelog).

**Comment by din14970** [comment]
I'm attempting to create a fix now
