### ISSUE TITLE
Memory usage in template library generation

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#24]
Template libraries can get very large if all symmetry inequivalent diffraction patterns are simulated for multiple low-symmetry crystal structures. We need to come up with a more memory efficient way of producing and using such libraries.

**Comment by shogas** [comment]
I'll have a look sometime this week(end), and at least summarize the current state here so that we can discuss alternatives.

**Comment by shogas** [comment]
Initial look:
 - The structure library size is quite small, but generating it can be sped up quite a bit
 - The memory problem that inspired this issue is in `IndexationGenerator::correlate` (in pyxem), not the template library itself

The `correlate` function pre-allocates a numpy array and fills it with data to calculate multiple correlation scores at once, as it is more efficient to hand off a large calculation to numpy at once than in many small steps. The size of this array was only tested for cubic structures, and is unnecessarily large for less symmetric structures. I'll see if I can find a better way to balance CPU/memory.

**Comment by dnjohnstone** [comment]
@pc494 Do you think we want to do anything about this - or rather close and move on?

**Comment by pc494** [comment]
I think this issue is deprecated in it's current form. I anticipate having a lot of these problems resolved in the 2020 Q2 cycle.
