### ISSUE TITLE
Bug in calculate_profile_data

### ISSUE THREAD

**Issue by ek456** [pyxem/diffsims#32]
`calculate_profile_data` - calculates a one dimensional diffraction profile for a structure.

**Describe the bug**
It does not return the correct multiplicity of generated planes

Problem is in line 237: `peaks[g_hkl] = [i_hkl, [tuple(hkl)], d_hkl]`

Planes  from the same family have the same spacing in reciprocal space (g_hkl) which means that planes from the same family overwrite each other.

**Possible solution** 
Instead of defining a dictionary of peaks, create list:
`peaks.append([g_hkl, i_hkl, [tuple(hkl)], d_hkl])` and then feed `peaks[2]` into get_unique_families. Currently working on that. 

**Notes**
Have tested `get_unique_families` separately and that function seems to work fine.

**Comment by pc494** [comment]
The problem lies within the following section (function starts at line 179 in https://github.com/pyxem/diffsims/blob/11c75ba262525d080e6a64c90812ce17077559b6/diffsims/generators/diffraction_generator.py) - I have removed code that isn't an issue but is needed to preserve indents.

```
for hkl, g_hkl in zip(spot_indices[mask], spot_distances[mask]):
            """ code removed for reading clarity """
            peaks[g_hkl] = [i_hkl, [tuple(hkl)], d_hkl]

        """ post processing code - removed for clarity """
```

The problem is that `peaks[g_hkl]` overwrites old dictionary entries with the same g_hkl (this a distance from the diffracting spot to the direct beam). There are multiple correct right hand sides to assignment of `peaks[g_hkl]`, which leads to the bug. In contrast, `tuple(hkl)` is a unique key.

cc: @isabelwood100, @dnjohnstone
