### ISSUE TITLE
Bug in get_grid_around_beam_direction()

### ISSUE THREAD

**Issue by norskie** [pyxem/diffsims#70]
**Describe the bug**
get_grid_around_beam_direction() works for beam directions [1,0,0] and [0,1,0] but not for [001]

**To Reproduce**
`from diffsims.generators.rotation_list_generators import get_grid_around_beam_direction
rot_list = get_grid_around_beam_direction([0,0,1], 5)`

**Expected behavior**
Should work for the family of directions <1,0,0>.

**Screenshots**
Traceback:
https://imgur.com/a/IDa8Ogc

**Comment by pc494** [comment]
This is an issue relating to unreleased development code. This functionality was fixed by #62 - installing from `master` should solve this problem.

**Comment by norskie** [comment]
Thank you for the quick reply @pc494.
I understand the problem now. 

So for future reference. A two-environment setup, one with the development version and one with the `master` version, is the best way to check whether the problem stems from unreleased development code or from something else?

**Comment by norskie** [comment]
Hi again @pc494,

I've attempted to fix the problem by installing from (what I thought) was master by the following steps:

I made a fresh conda environment "pyxem_master"

Where I installed pyxem (containing diffsims) by 
`conda install -c conda-forge pyxem`

Which I believed to be the `master` version?

However, as the following screenshots show, the diffsims.generators.rotation_list_generators module cannot be found there. 

Traceback:
![Screenshot from 2020-02-12 20-04-40](https://user-images.githubusercontent.com/43781509/74367970-0c6b0580-4dd3-11ea-82ca-c4f6d86ff081.png)

Attempting to regex the function with no hits.
![Screenshot from 2020-02-12 20-00-20](https://user-images.githubusercontent.com/43781509/74367974-0d039c00-4dd3-11ea-9851-5261491f0817.png)

What am I doing wrong? I am still quite new to this, so much of the lingo is new to me.

Thank you again.

**Comment by pc494** [comment]
@norskie 

This will be a little long but I hope it will clear things up:
`conda install pyxem`
install the latest "release version" of pyxem, when it does that pyxem tells it to install a "release version" of diffsims. In this case pyxem is at `0.10.0` and diffsims at `0.1.5`.

"release versions" of code are special. They never change (this is because we obey a thing called semantic versioning). This make debugging issues that arise from them easier as we know exactly what code exists on your machine.

diffsims `0.1.5` was release a little while back (you can look it up on the github) - the code you have been working on has been off the `master` branch. `master` is a github term, but for our case it means the most "up to date" version of the code. The issue you originally raised arose from an installed diffsims version from master (it's called `0.2.0dev`) - but since you install it we've made changes to `master`. To get these changes you need to navigate to your diffsims install where you edit diffsims code (if you don't have one of these start by running the appropriate `git clone`).

Then navigate to that directory. Run
`git pull upstream master`
`git log`
`pip install .`

The first line makes sure the diffsims folder on your machine is the same as the one on the internet (at pyxem/diffsims). The second step lets you check that (the top entry should be the most recent commit with message) - to get out of that view you type `:q <enter>` (at least on linux you do). The final line installs to your environment `diffsims` as it exists in that folder.

I hope that helps :)

**Comment by EirikOpheim** [comment]
Hello, Phillip! 

Endre and I tried to install the most recent version now, but we both end up having the issue of a few missing files. I see that in every folder there is an __init__.py file, usually containing the license terms and nothing else. I can't find this file in the most recent version of diffsims in the folder utils/atomic_diffraction_generator_support. Could this be an issue? 

Eirik

**Comment by pc494** [comment]
Okay, that's a little surprising. I have some questions.

Which files do you think are missing? Why do you think they are missing? Where does this lead to an error?

I would be surprised if the absent `__init__` you mention is causing this problem, but I've been surprised before... :)

**Comment by norskie** [comment]
@pc494, after discussion with Eirik, the `__init__.py` was found to be the culprit for the abovementioned problem, #71 fixes this I believe. Seems like `__init__.py` is required when installing in order to get the folder built into the environment.

The folder that is missing is diffsims/utils/atomic_diffraction_generator_support.

**Comment by EirikOpheim** [comment]
The problem was resolved when I added the __init__ locally on my computer within the folder utils/atomic_diffraction_generator_support. 

I believe only the __init__.py file is missing, and that none of the files within utils/atomic_diffraction_generator_support are found by the compiler without the __init__.py file.

Error on my CPU was in loading pyxem, with error message stating that a specific file from diffsims was not found.

**Comment by pc494** [comment]
Seems fair to me, was wondering if it was the stuff discussed in https://github.com/pyxem/pyxem/pull/538 but I'll merge the extra `__init__` so that it's there for the release version.

**Comment by pc494** [comment]
#71 is merged in, so I'm closing this if there are no objections.

**Comment by EirikOpheim** [comment]
Sounds good! :)
